### ISSUE TITLE
No database selected

### ISSUE THREAD

**Issue by hugh-nguyen** [dbeatty10/dbt-mysql#112]
### Describe the bug
Hi I've just set up a brand new project using db init and dbt-mysql. I've setup my profiles.yaml and checked that dbt debug connects to my database properly and returns no errors.

When I run ```dbt run```, I get the following error
![image](https://user-images.githubusercontent.com/30641101/194739462-482ea34e-cefb-401f-9b53-3482f62d2f33.png)

How do I specify the database in dbt?

**Comment by hugh-nguyen** [comment]
Still totally stuck on this, below is a copy of my profiles.yml
```
puddle:
  target: dev
  outputs:
    dev:
      type: mysql5
      server: localhost
      port: 3306  # optional
      database: puddle
      dbname: puddle
      schema: puddle
      username: test
      password: test
      driver: MySQL ODBC 8.0 ANSI Driver
    prod:
      type: mysql5
      server: [server/host]
      port: [port]  # optional
      database: [schema] # optional, should be same as schema
      schema: [schema]
      username: [username]
      password: [password]
      driver: MySQL ODBC 8.0 ANSI Driver
```
