### ISSUE TITLE
MariaDB 11.5.2: Unknown collation `utf8mb4_0900_ai_ci`

### ISSUE THREAD

**Issue by thenaturalist** [dbeatty10/dbt-mysql#176]
### Describe the bug
Unknown collation breaking adapter

### Steps To Reproduce
- Install `1.7.0`
- set up profile against MariaDB 11.5.2
- run `dbt debug`, see error `1273 (HY000): Unknown collation: 'utf8mb4_0900_ai_ci'`

### Expected behavior
dbt runs without issue.

**The output of `dbt --version`:**
```
Core:
  - installed: 1.7.18
  - latest:    1.8.8  - Update available!

  Your version of dbt-core is out of date!
  You can find instructions for upgrading here:
  https://docs.getdbt.com/docs/installation

Plugins:
  - mysql5:  1.7.0 - Could not determine latest version
  - mariadb: 1.7.0 - Could not determine latest version
  - mysql:   1.7.0 - Up to date!
```

**The operating system you're using:**
macOS Sequoia 15.1

**The output of `python --version`:**
Python 3.12.7
