### ISSUE TITLE
dbt docs generate: Expected only one database in get_catalog

### ISSUE THREAD

**Issue by stevenbeeckman** [dbeatty10/dbt-mysql#58]
### Describe the bug
I was trying to generate docs for my projects (to check out dbt's data lineage feature) but it gave the below error. 

I'm not sure if I should register `information_schema` as another source in my `source.yml` file (so I could use `{{ source() }}`)?

```
$ dbt docs generate
Running with dbt=0.19.0
Found 8 models, 2 tests, 0 snapshots, 0 analyses, 140 macros, 0 operations, 0 seed files, 2 sources, 0 exposures

21:41:44 | Concurrency: 4 threads (target='tst')
21:41:44 |
21:41:45 | Done.
21:41:45 | Building catalog
Encountered an error:
Compilation Error
  Expected only one database in get_catalog, found [<InformationSchema INFORMATION_SCHEMA>, <InformationSchema villo.INFORMATION_SCHEMA>]
```

### Steps To Reproduce
In as much detail as possible, please provide steps to reproduce the issue. Sample data that triggers the issue, example model code, etc is all very helpful here.

I have a file called `source.yml` in my `models` folder so I can refer to some tables using the `{{ source() }}` feature.

These are the first 8 lines of `source.yml`:

```
version: 2

sources:
  - name: villo
    description: The database containing all the measurements.
    database: villo

    tables:
```

This is my `profiles.yml`:

```
sm_villo:
  target: tst
  outputs:
    tst:
      type: mysql
      server: localhost
      user: ************
      password: ***************
      schema: villo
      threads: 4
```

I ran `dbt docs generate`.

### Expected behavior

HTML documentation is generated.

### Screenshots and log output

**The output of `dbt --version`:**
```
installed version: 0.19.0
   latest version: 0.19.0

Up to date!

Plugins:
  - postgres: 0.19.0
  - bigquery: 0.19.0
  - mysql: 0.19.0
  - snowflake: 0.19.0
  - mysql5: 0.19.0
  - redshift: 0.19.0
```

**The operating system you're using:**

Ubuntu 20.04.2 LTS (GNU/Linux 5.4.0-62-generic x86_64)

**The output of `python --version`:**

Python 3.8.5
